linters-settings:
  govet:
    enable:
      - shadow
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - hugeParam
      - rangeValCopy

linters:
  disable-all: true
  enable:
    - copyloopvar
    - gochecknoinits
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - unconvert
    - unused

  fast: false


issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - text: "should have a package comment, unless it's in another file for this package"
      linters:
        - golint
    - text: "exitAfterDefer:"
      linters:
        - gocritic
    - text: "whyNoLint: include an explanation for nolint directive"
      linters:
        - gocritic
    - text: "go.mongodb.org/mongo-driver/bson/primitive.E"
      linters:
        - govet
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
    - text: "should have a package comment"
      linters:
        - revive
    - text: 'Deferring unsafe method "Close" on type "io.ReadCloser"'
      linters:
        - gosec
    - linters:
        - unparam
        - unused
        - revive
      path: _test\.go$
      text: "unused-parameter"
  exclude-use-default: false
