language: go

services:
  - mongodb

go:
  - "1.11.x"

install: true

before_install:
  - export TZ=America/Chicago
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
  - go get github.com/mattn/goveralls
  - export MONGO_TEST=mongodb://127.0.0.1:27017
  - export PATH=$(pwd)/bin:$PATH

script:
  - GO111MODULE=on go get ./...
  - GO111MODULE=on go mod vendor
  - GO111MODULE=on go test  -v -mod=vendor -covermode=count -coverprofile=profile.cov ./... || travis_terminate 1;
  - golangci-lint run --tests=false  || travis_terminate 1;
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
