package user
//go:cgo_import_dynamic __libc_start_main __libc_start_main#GLIBC_2.34 "libc.so.6"
//go:cgo_import_dynamic _ITM_deregisterTMCloneTable _ITM_deregisterTMCloneTable ""
//go:cgo_import_dynamic getpwuid_r getpwuid_r#GLIBC_2.2.5 "libc.so.6"
//go:cgo_import_dynamic __gmon_start__ __gmon_start__ ""
//go:cgo_import_dynamic getgrgid_r getgrgid_r#GLIBC_2.2.5 "libc.so.6"
//go:cgo_import_dynamic getpwnam_r getpwnam_r#GLIBC_2.2.5 "libc.so.6"
//go:cgo_import_dynamic getgrouplist getgrouplist#GLIBC_2.2.5 "libc.so.6"
//go:cgo_import_dynamic sysconf sysconf#GLIBC_2.2.5 "libc.so.6"
//go:cgo_import_dynamic getgrnam_r getgrnam_r#GLIBC_2.2.5 "libc.so.6"
//go:cgo_import_dynamic _ITM_registerTMCloneTable _ITM_registerTMCloneTable ""
//go:cgo_import_dynamic __cxa_finalize __cxa_finalize#GLIBC_2.2.5 "libc.so.6"
//go:cgo_import_dynamic _ _ "libc.so.6"
