package net
//go:cgo_import_dynamic res_search res_search#GLIBC_2.34 "libc.so.6"
//go:cgo_import_dynamic free free#GLIBC_2.2.5 "libc.so.6"
//go:cgo_import_dynamic __libc_start_main __libc_start_main#GLIBC_2.34 "libc.so.6"
//go:cgo_import_dynamic __errno_location __errno_location#GLIBC_2.2.5 "libc.so.6"
//go:cgo_import_dynamic _ITM_deregisterTMCloneTable _ITM_deregisterTMCloneTable ""
//go:cgo_import_dynamic gai_strerror gai_strerror#GLIBC_2.2.5 "libc.so.6"
//go:cgo_import_dynamic getnameinfo getnameinfo#GLIBC_2.2.5 "libc.so.6"
//go:cgo_import_dynamic __gmon_start__ __gmon_start__ ""
//go:cgo_import_dynamic malloc malloc#GLIBC_2.2.5 "libc.so.6"
//go:cgo_import_dynamic _ITM_registerTMCloneTable _ITM_registerTMCloneTable ""
//go:cgo_import_dynamic getaddrinfo getaddrinfo#GLIBC_2.2.5 "libc.so.6"
//go:cgo_import_dynamic freeaddrinfo freeaddrinfo#GLIBC_2.2.5 "libc.so.6"
//go:cgo_import_dynamic __cxa_finalize __cxa_finalize#GLIBC_2.2.5 "libc.so.6"
//go:cgo_import_dynamic _ _ "libc.so.6"
